package com.pontoevirgulasoftwaresolutions.builders;

import j2html.tags.ContainerTag;

import static j2html.TagCreator.*;

public class HtmlReportBuilder implements ReportBuilder
{
    private ContainerTag body;
    private ContainerTag document;

    public HtmlReportBuilder(){
        body = body();
        document = html(
                head(),
                body
        );
    }


    @Override
    public void buildHeader() {
        body.with(h1("Report in HTML"));
    }

    @Override
    public void buildBody() {
        body.with(
                p("This is a paragraph"),
                p("It's just an example.")
        );
    }

    @Override
    public void buildFooter() {
        body.with(footer("This HTML was generated by the HtmlReportBuilder!"));
    }
}
